/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2014-11-17 18:43:33 UTC)
 * on 2014-11-27 at 08:17:01 UTC 
 * Modify at your own risk.
 */

package com.appspot.tyndr_server.tyndr.model;

/**
 * Passes information about a new ad from the endpoint to the backend. Author: Kristjan Eldjarn
 * Hjorleifsson, keh4@hi.is
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the tyndr. For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class MessagesCreateAdvertMessage extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long age;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String color;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String description;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String fur;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key("image_string")
  private java.lang.String imageString;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String label;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double lat;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Double lon;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String name;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String sex;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String species;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String subspecies;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getAge() {
    return age;
  }

  /**
   * @param age age or {@code null} for none
   */
  public MessagesCreateAdvertMessage setAge(java.lang.Long age) {
    this.age = age;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getColor() {
    return color;
  }

  /**
   * @param color color or {@code null} for none
   */
  public MessagesCreateAdvertMessage setColor(java.lang.String color) {
    this.color = color;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getDescription() {
    return description;
  }

  /**
   * @param description description or {@code null} for none
   */
  public MessagesCreateAdvertMessage setDescription(java.lang.String description) {
    this.description = description;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getFur() {
    return fur;
  }

  /**
   * @param fur fur or {@code null} for none
   */
  public MessagesCreateAdvertMessage setFur(java.lang.String fur) {
    this.fur = fur;
    return this;
  }

  /**
   * @see #decodeImageString()
   * @return value or {@code null} for none
   */
  public java.lang.String getImageString() {
    return imageString;
  }

  /**

   * @see #getImageString()
   * @return Base64 decoded value or {@code null} for none
   *
   * @since 1.14
   */
  public byte[] decodeImageString() {
    return com.google.api.client.util.Base64.decodeBase64(imageString);
  }

  /**
   * @see #encodeImageString()
   * @param imageString imageString or {@code null} for none
   */
  public MessagesCreateAdvertMessage setImageString(java.lang.String imageString) {
    this.imageString = imageString;
    return this;
  }

  /**

   * @see #setImageString()
   *
   * <p>
   * The value is encoded Base64 or {@code null} for none.
   * </p>
   *
   * @since 1.14
   */
  public MessagesCreateAdvertMessage encodeImageString(byte[] imageString) {
    this.imageString = com.google.api.client.util.Base64.encodeBase64URLSafeString(imageString);
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getLabel() {
    return label;
  }

  /**
   * @param label label or {@code null} for none
   */
  public MessagesCreateAdvertMessage setLabel(java.lang.String label) {
    this.label = label;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getLat() {
    return lat;
  }

  /**
   * @param lat lat or {@code null} for none
   */
  public MessagesCreateAdvertMessage setLat(java.lang.Double lat) {
    this.lat = lat;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Double getLon() {
    return lon;
  }

  /**
   * @param lon lon or {@code null} for none
   */
  public MessagesCreateAdvertMessage setLon(java.lang.Double lon) {
    this.lon = lon;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getName() {
    return name;
  }

  /**
   * @param name name or {@code null} for none
   */
  public MessagesCreateAdvertMessage setName(java.lang.String name) {
    this.name = name;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSex() {
    return sex;
  }

  /**
   * @param sex sex or {@code null} for none
   */
  public MessagesCreateAdvertMessage setSex(java.lang.String sex) {
    this.sex = sex;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSpecies() {
    return species;
  }

  /**
   * @param species species or {@code null} for none
   */
  public MessagesCreateAdvertMessage setSpecies(java.lang.String species) {
    this.species = species;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getSubspecies() {
    return subspecies;
  }

  /**
   * @param subspecies subspecies or {@code null} for none
   */
  public MessagesCreateAdvertMessage setSubspecies(java.lang.String subspecies) {
    this.subspecies = subspecies;
    return this;
  }

  @Override
  public MessagesCreateAdvertMessage set(String fieldName, Object value) {
    return (MessagesCreateAdvertMessage) super.set(fieldName, value);
  }

  @Override
  public MessagesCreateAdvertMessage clone() {
    return (MessagesCreateAdvertMessage) super.clone();
  }

}
